batch_size: 1024
choice_mode: heterogeneous
core_vars:
- x1
- x2
- x3
embedding_dims: !!python/object/apply:collections.OrderedDict
- - - e1
    - 3
  - - e2
    - 3
  - - o1
    - 4
embedding_mode: shared
embedding_vars:
- e1
- e2
- o1
learning_rate: 0.003
max_epochs: 50
n_alternatives: 2
n_latent_classes: 3
random_state: 5723588
segmentation_dropout_rate: 0.15
segmentation_hidden_dims:
- 128
- 128
segmentation_net_dims:
- 7
- 128
- 128
- 3
segmentation_vars:
- s1_s11
- s1_s12
- s1_s13
- s2_s21
- s2_s22
- s2_s23
- dist
segmentation_vars_categorical:
- s1
- s2
segmentation_vars_continuous:
- dist
test_size: 0.25
weight_decay_embedding: 0.0001
weight_decay_segmentation: 0.01
